project:
  type: website
  output-dir: docs

website:
  title: "Data Analysis, Modelling, and Decision-Making"
  twitter-card: 
    creator: "@PieRatio"
  navbar:
    logo: "AGSMlogo.jpeg"
#    background: "lavender"
#    foreground: "purple"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/robertwwalker/DADM-FAQ
      - icon: twitter
        href: https://twitter.com/PieRatio
format:
  html:
    theme: morph
    css: styles.css
#    backgroundcolor: "purple"
